variables:
  ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
    ENABLE_LONG_RUNNING_TESTS: true
    ENABLE_COMPLIANCE: true

jobs:
  - job: buildLinux
    displayName: Build - Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: common/setup.yml
      - template: common/lint.yml
      - template: common/build.yml
      - template: common/package.yml
      - template: common/sbom.yml # Only generate on linux
    variables:
      Codeql.Enabled: $[in(variables['Build.Reason'], 'Schedule')] # Enable CodeQL only on scheduled builds because it is slow

  - job: Windows
    displayName: Compliance - Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: common/setup.yml
      - template: common/build.yml
      - template: compliance/compliance.yml # Only works on Windows

  - job: Windows
    displayName: Test - Windows
    pool:
      vmImage: windows-latest
    steps:
      - template: common/setup.yml
      # - template: common/lint.yml
      - template: common/build.yml
      # - template: common/package.yml
      - template: compliance/compliance.yml # Only works on Windows
      - template: common/test.yml

  - job: testLinux
    displayName: Test - Linux
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: common/setup.yml
      - template: common/build.yml
      - template: common/test.yml
    variables:
      Codeql.Enabled: $[in(variables['Build.Reason'], 'Schedule')] # Enable CodeQL only on scheduled builds because it is slow

  - job: macOS
    displayName: Test - macOS
    pool:
      vmImage: macOS-latest
    steps:
      - template: common/setup.yml
      - template: common/build.yml
      - template: common/test.yml

trigger:
  branches:
    include:
      - "*"

pr:
  branches:
    include:
      - "*"

schedules:
  - cron: "30 7 * * *"
    displayName: Nightly at 12:30 PT
    always: true # Run even when there are no code changes
    branches:
      include:
        - main
